const $=s=>document.querySelector(s),state={token:localStorage.getItem("it_token")||"",user:null};
async function api(path,opt={}){const h={"Content-Type":"application/json",...(opt.headers||{})};if(state.token)h.Authorization=`Bearer ${state.token}`;const r=await fetch("/api"+path,{...opt,headers:h}),d=await r.json().catch(()=>({success:false,error:"Invalid response"}));if(r.status===401){logout(false);throw Error(d.error||"Session expired")}if(!r.ok||d.success===false)throw Error(d.error||"Request gagal");return d}
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])),money=n=>n?new Intl.NumberFormat("id-ID").format(n):"Negotiable";
function toast(m){const x=$("#toast");x.textContent=m;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2800)}
function nav(){const n=$("#nav"),a=$("#account");if(!state.user){n.innerHTML=`<button onclick="home()">Jobs</button><button onclick="login()">Login</button><button onclick="register()">Register</button>`;a.textContent=""}else{n.innerHTML=`<button onclick="dashboard()">Dashboard</button><button onclick="jobs()">Jobs</button>${state.user.role!=="candidate"?`<button onclick="companyJobs()">My Jobs</button>`:""}<button onclick="applications()">Applications</button>`;a.innerHTML=`${esc(state.user.name)} · <button class="linkbtn" onclick="logout()">Logout</button>`}}
function jobCard(j){return `<article class="card job"><span class="pill">${esc(j.employment_type)}</span><h3>${esc(j.title)}</h3><div class="muted">${esc(j.company_name||"Company")} · ${esc(j.location||"Indonesia")}</div><p>${esc((j.description||"").slice(0,140))}</p><div class="muted">Rp ${money(j.salary_min)} – Rp ${money(j.salary_max)}</div><div class="actions"><button class="btn" onclick="jobDetail('${j.id}')">View Job</button></div></article>`}
function home(){nav();$("#view").innerHTML=`<section class="hero"><div class="container"><h1>Recruitment ERP untuk mengelola talent dari awal sampai hiring.</h1><p>Indo-Talent menyatukan candidate, company, job, application dan recruitment pipeline dalam satu platform.</p><div class="actions"><button class="btn" onclick="jobs()">Lihat Lowongan</button>${state.user?`<button class="btn secondary" onclick="dashboard()">Dashboard</button>`:`<button class="btn secondary" onclick="register()">Daftar</button>`}</div></div></section><div class="container"><div class="sectionhead"><h2>Lowongan Terbaru</h2></div><div id="homejobs" class="grid"></div></div>`;api("/jobs").then(d=>$("#homejobs").innerHTML=d.jobs.slice(0,6).map(jobCard).join("")||`<div class="empty">Belum ada lowongan.</div>`).catch(e=>toast(e.message))}
async function jobs(){const d=await api("/jobs");$("#view").innerHTML=`<div class="container"><div class="sectionhead"><h2>Job Vacancies</h2></div><div class="grid">${d.jobs.map(jobCard).join("")||`<div class="empty">Belum ada lowongan.</div>`}</div></div>`}
async function jobDetail(id){try{const j=(await api("/jobs/"+id)).job;$("#view").innerHTML=`<div class="container"><button class="linkbtn" onclick="jobs()">← Back</button><div class="card"><span class="pill">${esc(j.employment_type)}</span><h1>${esc(j.title)}</h1><p class="muted">${esc(j.company_name)} · ${esc(j.location)}</p><h3>Description</h3><p>${esc(j.description).replace(/\n/g,"<br>")}</p><h3>Requirements</h3><p>${esc(j.requirements).replace(/\n/g,"<br>")}</p><h3>Benefits</h3><p>${esc(j.benefits||"—").replace(/\n/g,"<br>")}</p><p><strong>Salary:</strong> Rp ${money(j.salary_min)} – Rp ${money(j.salary_max)}</p>${state.user?.role==="candidate"?`<button class="btn" onclick="applyJob('${j.id}')">Apply Now</button>`:!state.user?`<button class="btn" onclick="login()">Login untuk Apply</button>`:""}</div></div>`}catch(e){toast(e.message)}}
async function applyJob(id){const cover=prompt("Cover letter / pesan recruiter:")||"";try{await api(`/jobs/${id}/apply`,{method:"POST",body:JSON.stringify({cover_letter:cover})});toast("Lamaran berhasil dikirim");applications()}catch(e){toast(e.message)}}
function login(){$("#view").innerHTML=`<div class="container"><div class="card form"><h2>Login</h2><form onsubmit="doLogin(event)"><div class="field"><label>Email</label><input id="email" type="email" required></div><div class="field"><label>Password</label><input id="password" type="password" required></div><button class="btn">Login</button></form><p class="muted">Demo admin: admin@indo-talent.my.id / Admin123!</p></div></div>`}
async function doLogin(e){e.preventDefault();try{const d=await api("/auth/login",{method:"POST",body:JSON.stringify({email:$("#email").value,password:$("#password").value})});state.token=d.token;state.user=d.user;localStorage.setItem("it_token",state.token);nav();dashboard()}catch(x){toast(x.message)}}
function register(){$("#view").innerHTML=`<div class="container"><div class="card form"><h2>Create Account</h2><form onsubmit="doRegister(event)"><div class="field"><label>Nama</label><input id="rname" required></div><div class="field"><label>Email</label><input id="remail" type="email" required></div><div class="field"><label>Password</label><input id="rpass" type="password" minlength="8" required></div><div class="field"><label>Role</label><select id="rrole"><option value="candidate">Candidate</option><option value="company">Company</option></select></div><div class="field"><label>Company Name</label><input id="rcompany"></div><button class="btn">Register</button></form></div></div>`}
async function doRegister(e){e.preventDefault();try{await api("/auth/register",{method:"POST",body:JSON.stringify({name:$("#rname").value,email:$("#remail").value,password:$("#rpass").value,role:$("#rrole").value,company_name:$("#rcompany").value})});toast("Registrasi berhasil");login()}catch(x){toast(x.message)}}
function logout(show=true){if(state.token)fetch("/api/auth/logout",{method:"POST",headers:{Authorization:`Bearer ${state.token}`}}).catch(()=>{});state.token="";state.user=null;localStorage.removeItem("it_token");nav();home();if(show)toast("Logout berhasil")}
async function dashboard(){if(!state.user)return login();if(state.user.role==="admin")return adminDashboard();if(state.user.role==="company")return companyDashboard();const d=await api("/applications");$("#view").innerHTML=`<div class="container"><div class="sectionhead"><h2>Candidate Dashboard</h2><button class="btn" onclick="profile()">Edit Profile</button></div><div class="stats"><div class="card stat">Applications<strong>${d.applications.length}</strong></div><div class="card stat">Interview<strong>${d.applications.filter(x=>x.status==="Interview").length}</strong></div><div class="card stat">Hired<strong>${d.applications.filter(x=>x.status==="Hired").length}</strong></div><div class="card stat">Profile<strong>Active</strong></div></div></div>`}
async function companyDashboard(){const[j,a]=await Promise.all([api("/company/jobs"),api("/applications")]);$("#view").innerHTML=`<div class="container"><div class="sectionhead"><h2>Company Dashboard</h2><button class="btn" onclick="newJob()">+ Post Job</button></div><div class="stats"><div class="card stat">Jobs<strong>${j.jobs.length}</strong></div><div class="card stat">Applicants<strong>${a.applications.length}</strong></div><div class="card stat">Shortlisted<strong>${a.applications.filter(x=>x.status==="Shortlisted").length}</strong></div><div class="card stat">Hired<strong>${a.applications.filter(x=>x.status==="Hired").length}</strong></div></div></div>`}
async function adminDashboard(){const d=await api("/admin/stats");$("#view").innerHTML=`<div class="container"><h2>Admin Dashboard</h2><div class="stats"><div class="card stat">Users<strong>${d.stats.users}</strong></div><div class="card stat">Companies<strong>${d.stats.companies}</strong></div><div class="card stat">Candidates<strong>${d.stats.candidates}</strong></div><div class="card stat">Applications<strong>${d.stats.applications}</strong></div></div></div>`}
async function applications(){if(!state.user)return login();const d=await api("/applications");$("#view").innerHTML=`<div class="container"><h2>Applications</h2><div class="tablewrap"><table class="table"><thead><tr><th>Candidate / Job</th><th>Company</th><th>Status</th><th>Date</th>${state.user.role!=="candidate"?"<th>Update</th>":""}</tr></thead><tbody>${d.applications.map(a=>`<tr><td><strong>${esc(state.user.role==="candidate"?a.title:a.candidate_name)}</strong><br><span class="muted">${esc(state.user.role==="candidate"?a.location:a.candidate_email)}</span></td><td>${esc(a.company_name||"")}</td><td><span class="pill">${esc(a.status)}</span></td><td>${new Date(a.created_at).toLocaleDateString("id-ID")}</td>${state.user.role!=="candidate"?`<td><select onchange="updateStatus('${a.id}',this.value)">${["Applied","Screening","Shortlisted","Interview","Test","Offer","Hired","Rejected"].map(s=>`<option ${s===a.status?"selected":""}>${s}</option>`).join("")}</select></td>`:""}</tr>`).join("")||`<tr><td colspan="5" class="empty">Belum ada data.</td></tr>`}</tbody></table></div></div>`}
async function updateStatus(id,status){try{await api("/applications/"+id,{method:"PUT",body:JSON.stringify({status})});toast("Status diperbarui")}catch(e){toast(e.message)}}
async function companyJobs(){const d=await api("/company/jobs");$("#view").innerHTML=`<div class="container"><div class="sectionhead"><h2>My Jobs</h2><button class="btn" onclick="newJob()">+ Post Job</button></div><div class="grid">${d.jobs.map(jobCard).join("")||`<div class="empty">Belum ada job.</div>`}</div></div>`}
function newJob(){$("#view").innerHTML=`<div class="container"><div class="card form"><h2>Post New Job</h2><form onsubmit="saveJob(event)"><div class="field"><label>Job Title</label><input id="jt" required></div><div class="field"><label>Location</label><input id="jl"></div><div class="grid2"><div class="field"><label>Employment</label><select id="je"><option>Full Time</option><option>Contract</option><option>Part Time</option></select></div><div class="field"><label>Workplace</label><select id="jw"><option>On-site</option><option>Hybrid</option><option>Remote</option></select></div></div><div class="grid2"><div class="field"><label>Salary Min</label><input id="jsmin" type="number"></div><div class="field"><label>Salary Max</label><input id="jsmax" type="number"></div></div><div class="field"><label>Description</label><textarea id="jd"></textarea></div><div class="field"><label>Requirements</label><textarea id="jr"></textarea></div><div class="field"><label>Benefits</label><textarea id="jb"></textarea></div><button class="btn">Publish Job</button></form></div></div>`}
async function saveJob(e){e.preventDefault();try{await api("/jobs",{method:"POST",body:JSON.stringify({title:$("#jt").value,location:$("#jl").value,employment_type:$("#je").value,workplace_type:$("#jw").value,salary_min:$("#jsmin").value,salary_max:$("#jsmax").value,description:$("#jd").value,requirements:$("#jr").value,benefits:$("#jb").value})});toast("Job berhasil dibuat");companyJobs()}catch(x){toast(x.message)}}
async function profile(){const d=await api("/me"),p=d.profile||{};$("#view").innerHTML=`<div class="container"><div class="card form"><h2>Profile</h2><form onsubmit="saveProfile(event)"><div class="field"><label>Name</label><input id="pn" value="${esc(d.user.name)}"></div><div class="field"><label>Phone</label><input id="pp" value="${esc(d.user.phone)}"></div><div class="field"><label>Company Name</label><input id="pc" value="${esc(d.user.company_name)}"></div><div class="field"><label>Headline</label><input id="ph" value="${esc(p.headline)}"></div><div class="field"><label>Education</label><textarea id="pe">${esc(p.education)}</textarea></div><div class="field"><label>Experience</label><textarea id="px">${esc(p.experience)}</textarea></div><div class="field"><label>Skills</label><textarea id="ps">${esc(p.skills)}</textarea></div><button class="btn">Save Profile</button></form></div></div>`}
async function saveProfile(e){e.preventDefault();try{await api("/me",{method:"PUT",body:JSON.stringify({name:$("#pn").value,phone:$("#pp").value,company_name:$("#pc").value,headline:$("#ph").value,education:$("#pe").value,experience:$("#px").value,skills:$("#ps").value})});state.user.name=$("#pn").value;nav();toast("Profile tersimpan")}catch(x){toast(x.message)}}
(async()=>{$("#year").textContent=new Date().getFullYear();if(state.token){try{state.user=(await api("/me")).user}catch{state.token="";localStorage.removeItem("it_token")}}nav();home()})();
