name = "indo-talent-erp"
main = "src/index.ts"
compatibility_date = "2026-08-19"

[vars]
APP_NAME = "AI Screening"

[[d1_databases]]
binding = "DB"
database_name = "indo-talent-db"
database_id = "5ad9a5b2-fdf2-4bd8-b1e9-ffc7d38ee0ae"
[[r2_buckets]]
binding = "CV_BUCKET"
bucket_name = "ai-screening-cv"

[observability]
enabled = true
