import { Hono } from "hono";
import { cors } from "hono/cors";
import { secureHeaders } from "hono/secure-headers";

interface Env {
  DB: D1Database;
  CV_BUCKET: R2Bucket;
  APP_NAME: string;
  OPENAI_API_KEY?: string;
  OPENAI_MODEL?: string;
  SESSION_SECRET?: string;
}

type AuthUser = { id:string; company_id:string; name:string; email:string; role:string; company_name:string };

const app = new Hono<{ Bindings: Env; Variables: { user: AuthUser } }>();
app.use("*", secureHeaders());
app.use("/api/*", cors({ origin: (origin) => origin || "*", allowMethods: ["GET","POST","PATCH","DELETE","OPTIONS"], allowHeaders: ["Content-Type","Authorization"], credentials: true }));
const id=()=>crypto.randomUUID(); const enc=new TextEncoder();
function b64url(bytes:Uint8Array){let binary="";for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function hex(bytes:Uint8Array){return [...bytes].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function sha256(v:string){return hex(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(v))))}
async function passwordHash(password:string){const salt=new Uint8Array(16);crypto.getRandomValues(salt);const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:120000,hash:"SHA-256"},key,256);return `pbkdf2$120000$${b64url(salt)}$${b64url(new Uint8Array(bits))}`}
async function passwordVerify(password:string,stored:string){try{const [scheme,it,saltText,expected]=stored.split("$");if(scheme!=="pbkdf2")return false;const sb=saltText.replace(/-/g,"+").replace(/_/g,"/");const bin=atob(sb+"=".repeat((4-sb.length%4)%4));const salt=Uint8Array.from(bin,c=>c.charCodeAt(0));const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:Number(it),hash:"SHA-256"},key,256);return b64url(new Uint8Array(bits))===expected}catch{return false}}
function cookieToken(req:Request){return (req.headers.get("Cookie")||"").match(/(?:^|;\s*)session=([^;]+)/)?.[1]||null}
function setCookie(token:string,maxAge:number){return `session=${token}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Lax`}
async function columns(db:D1Database,table:string){const r=await db.prepare(`PRAGMA table_info(${table})`).all<any>();return new Set((r.results||[]).map((x:any)=>String(x.name)))}
async function createSession(c:any,u:AuthUser){const raw=b64url(crypto.getRandomValues(new Uint8Array(32)));const cs=await columns(c.env.DB,"sessions");const tokenHash=await sha256(raw);const expires=new Date(Date.now()+7*86400000).toISOString();const fields:string[]=[];const vals:any[]=[];const add=(n:string,v:any)=>{if(cs.has(n)){fields.push(n);vals.push(v)}};if(cs.has("id"))add("id",tokenHash);else if(cs.has("session_id"))add("session_id",tokenHash);else if(cs.has("token_hash"))add("token_hash",tokenHash);else if(cs.has("token"))add("token",tokenHash);add("user_id",u.id);if(cs.has("company_id"))add("company_id",u.company_id);else if(cs.has("organization_id"))add("organization_id",u.company_id);add("expires_at",expires);if(cs.has("created_at"))add("created_at",new Date().toISOString());if(!fields.includes("user_id")||!fields.some(x=>["id","session_id","token_hash","token"].includes(x)))throw new Error("sessions_schema_missing_identity_columns");await c.env.DB.prepare(`INSERT INTO sessions(${fields.join(",")}) VALUES(${fields.map(()=>"?").join(",")})`).bind(...vals).run();c.header("Set-Cookie",setCookie(raw,7*86400))}
async function currentUser(c:any):Promise<AuthUser|null>{const raw=cookieToken(c.req.raw);if(!raw)return null;const cs=await columns(c.env.DB,"sessions");const tokenCol=cs.has("id")?"id":cs.has("session_id")?"session_id":cs.has("token_hash")?"token_hash":cs.has("token")?"token":null;if(!tokenCol||!cs.has("user_id")||!cs.has("expires_at"))return null;return await c.env.DB.prepare(`SELECT u.id,u.company_id,u.name,u.email,u.role,COALESCE(cp.company_name,u.name) company_name FROM sessions s JOIN users u ON u.id=s.user_id LEFT JOIN company_profiles cp ON cp.user_id=u.company_id WHERE s.${tokenCol}=? AND s.expires_at>CURRENT_TIMESTAMP LIMIT 1`).bind(await sha256(raw)).first<AuthUser>()}
async function requireAuth(c:any,next:any){const u=await currentUser(c);if(!u)return c.json({error:"unauthorized"},401);c.set("user",u);await next()}
async function audit(c:any,u:AuthUser,action:string,entityId?:string){try{const cs=await columns(c.env.DB,"admin_audit_logs");const fields:string[]=[];const vals:any[]=[];const add=(n:string,v:any)=>{if(cs.has(n)){fields.push(n);vals.push(v)}};add("id",id());add("user_id",u.id);add("action",action);add("entity_id",entityId||null);add("company_id",u.company_id);add("created_at",new Date().toISOString());if(fields.length)await c.env.DB.prepare(`INSERT INTO admin_audit_logs(${fields.join(",")}) VALUES(${fields.map(()=>"?").join(",")})`).bind(...vals).run()}catch{}}
async function appMeta(db:D1Database){const cs=await columns(db,"applications");return {cs,candidate:cs.has("candidate_id")?"candidate_id":cs.has("user_id")?"user_id":null,tenant:cs.has("company_id")?"company_id":cs.has("organization_id")?"organization_id":null}}
async function createApplication(c:any,u:AuthUser,jobId:string,candidateUserId:string){const m=await appMeta(c.env.DB);if(!m.candidate)throw new Error("applications_missing_candidate_key");const f=["id","job_id",m.candidate],v:any[]=[id(),jobId,candidateUserId];if(m.tenant){f.push(m.tenant);v.push(u.company_id)}if(m.cs.has("status")){f.push("status");v.push("Review")}if(m.cs.has("score")){f.push("score");v.push(0)}await c.env.DB.prepare(`INSERT INTO applications(${f.join(",")}) VALUES(${f.map(()=>"?").join(",")})`).bind(...v).run()}
app.get("/api/health",async c=>{try{await c.env.DB.prepare("SELECT 1").first();return c.json({ok:true,app:c.env.APP_NAME,version:"v6.2-schema-aligned",database:"indo-talent-db",storage:"r2"})}catch{return c.json({ok:false,error:"database_unavailable"},503)}});
app.post("/api/auth/register",async c=>{try{const b=await c.req.json<any>(),company=String(b.organization_name||"").trim(),name=String(b.name||"").trim(),email=String(b.email||"").trim().toLowerCase(),password=String(b.password||"");if(!company||!name||!email||password.length<10)return c.json({error:"organization_name,name,email,password_min_10_required"},400);if(await c.env.DB.prepare("SELECT id FROM users WHERE email=? LIMIT 1").bind(email).first())return c.json({error:"email_already_registered"},409);const uid=id(),hash=await passwordHash(password);await c.env.DB.batch([c.env.DB.prepare("INSERT INTO users(id,role,email,password_hash,name,status,company_id,approval_status,email_verified) VALUES(?,?,?,?,?,?,?,?,?)").bind(uid,"admin",email,hash,name,"active",uid,"approved",0),c.env.DB.prepare("INSERT INTO company_profiles(user_id,company_name,contact_name,contact_email,created_at,updated_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").bind(uid,company,name,email)]);const u:AuthUser={id:uid,company_id:uid,name,email,role:"admin",company_name:company};await createSession(c,u);await audit(c,u,"auth.register",uid);return c.json({user:u},201)}catch(e:any){return c.json({error:"registration_failed",detail:String(e?.message||e)},500)}});
app.post("/api/auth/login",async c=>{try{const b=await c.req.json<any>(),email=String(b.email||"").trim().toLowerCase(),password=String(b.password||"");const r=await c.env.DB.prepare("SELECT u.id,u.company_id,u.name,u.email,u.password_hash,u.role,COALESCE(cp.company_name,u.name) company_name FROM users u LEFT JOIN company_profiles cp ON cp.user_id=u.company_id WHERE u.email=? LIMIT 1").bind(email).first<any>();if(!r||!(await passwordVerify(password,r.password_hash)))return c.json({error:"invalid_credentials"},401);const u:AuthUser={id:r.id,company_id:r.company_id||r.id,name:r.name,email:r.email,role:r.role,company_name:r.company_name};await createSession(c,u);await audit(c,u,"auth.login",u.id);return c.json({user:u})}catch(e:any){return c.json({error:"login_failed",detail:String(e?.message||e)},500)}});
app.post("/api/auth/logout",async c=>{try{const raw=cookieToken(c.req.raw);const cs=await columns(c.env.DB,"sessions");const tokenCol=cs.has("id")?"id":cs.has("session_id")?"session_id":cs.has("token_hash")?"token_hash":cs.has("token")?"token":null;if(raw&&tokenCol)await c.env.DB.prepare(`DELETE FROM sessions WHERE ${tokenCol}=?`).bind(await sha256(raw)).run();c.header("Set-Cookie",setCookie("",0));return c.json({ok:true})}catch{return c.json({ok:true})}});
app.get("/api/auth/me",requireAuth,c=>c.json({user:c.get("user")}));
for(const p of ["/api/jobs","/api/candidates","/api/applications","/api/dashboard","/api/screenings/*"])app.use(p,requireAuth);
app.get("/api/dashboard",async c=>{const u=c.get("user") as AuthUser;const [j,ca,a]=await Promise.all([c.env.DB.prepare("SELECT COUNT(*) count FROM jobs WHERE company_id=?").bind(u.company_id).first<any>(),c.env.DB.prepare("SELECT COUNT(*) count FROM users WHERE company_id=? AND role='candidate'").bind(u.company_id).first<any>(),c.env.DB.prepare("SELECT COUNT(*) count FROM applications a JOIN jobs j ON j.id=a.job_id WHERE j.company_id=?").bind(u.company_id).first<any>()]);return c.json({jobs:j?.count||0,candidates:ca?.count||0,applications:a?.count||0,strong_matches:0})});
app.get("/api/jobs",async c=>{const u=c.get("user") as AuthUser;return c.json((await c.env.DB.prepare("SELECT id,title,location,salary,description,status,created_at FROM jobs WHERE company_id=? ORDER BY created_at DESC").bind(u.company_id).all()).results)});
app.post("/api/jobs",async c=>{const u=c.get("user") as AuthUser,b=await c.req.json<any>();if(!String(b.title||"").trim()||!String(b.description||"").trim())return c.json({error:"title,description_required"},400);const jid=id();await c.env.DB.prepare("INSERT INTO jobs(id,company_id,title,location,salary,description,status,created_at) VALUES(?,?,?,?,?,?,?,CURRENT_TIMESTAMP)").bind(jid,u.company_id,String(b.title).trim(),String(b.location||"").trim(),String(b.salary||"").trim(),String(b.description).trim(),"open").run();await audit(c,u,"job.create",jid);return c.json({id:jid},201)});
app.get("/api/candidates",async c=>{const u=c.get("user") as AuthUser;return c.json((await c.env.DB.prepare(`SELECT u.id,u.name,u.email,u.phone,cp.cv_url,cp.full_name,cp.headline,cp.summary FROM users u LEFT JOIN candidate_profiles cp ON cp.user_id=u.id WHERE u.company_id=? AND u.role='candidate' ORDER BY u.created_at DESC`).bind(u.company_id).all()).results)});
app.post("/api/candidates/upload",async c=>{try{const u=c.get("user") as AuthUser,f=await c.req.formData(),file=f.get("file"),name=String(f.get("name")||"").trim(),email0=String(f.get("email")||"").trim().toLowerCase(),phone=String(f.get("phone")||"").trim(),jobId=String(f.get("job_id")||"").trim();if(!(file instanceof File)||!name)return c.json({error:"file,name_required"},400);if(file.size>10*1024*1024)return c.json({error:"file_too_large_max_10mb"},413);const email=email0||`candidate-${crypto.randomUUID()}@internal.invalid`;if(await c.env.DB.prepare("SELECT id FROM users WHERE email=? LIMIT 1").bind(email).first())return c.json({error:"candidate_email_already_exists"},409);const uid=id(),key=`${u.company_id}/candidates/${uid}/${file.name.replace(/[^a-zA-Z0-9._-]+/g,"_").slice(0,160)||"cv"}`;await c.env.CV_BUCKET.put(key,file.stream(),{httpMetadata:{contentType:file.type||"application/octet-stream"}});const text=file.type==="text/plain"?(await file.text()).slice(0,100000):"";await c.env.DB.batch([c.env.DB.prepare("INSERT INTO users(id,role,email,password_hash,name,phone,status,company_id,approval_status) VALUES(?,?,?,?,?,?,?,?,?)").bind(uid,"candidate",email,"!cv-upload-no-login!",name,phone,"active",u.company_id,"approved"),c.env.DB.prepare("INSERT INTO candidate_profiles(user_id,phone,full_name,cv_url,summary) VALUES(?,?,?,?,?)").bind(uid,phone,name,key,text)]);if(jobId){const j=await c.env.DB.prepare("SELECT id FROM jobs WHERE id=? AND company_id=?").bind(jobId,u.company_id).first();if(j)await createApplication(c,u,jobId,uid)}await audit(c,u,"candidate.upload",uid);return c.json({id:uid,object_key:key,filename:file.name,extraction_status:file.type==="text/plain"?"complete":"pending"},201)}catch(e:any){return c.json({error:"candidate_upload_failed",detail:String(e?.message||e)},500)}});
app.get("/api/applications",async c=>{try{const u=c.get("user") as AuthUser,m=await appMeta(c.env.DB);if(!m.candidate)return c.json({error:"applications_missing_candidate_key"},500);const tenant=m.tenant?`AND a.${m.tenant}=?`:"";const sql=`SELECT a.id,a.status,a.score,j.id job_id,j.title job_title,cu.id candidate_id,cu.name candidate_name,cu.email candidate_email,cp.cv_url FROM applications a JOIN jobs j ON j.id=a.job_id JOIN users cu ON cu.id=a.${m.candidate} LEFT JOIN candidate_profiles cp ON cp.user_id=cu.id WHERE j.company_id=? ${tenant} ORDER BY a.rowid DESC`;const params=m.tenant?[u.company_id,u.company_id]:[u.company_id];return c.json((await c.env.DB.prepare(sql).bind(...params).all()).results)}catch(e:any){return c.json({error:"applications_query_failed",detail:String(e?.message||e)},500)}});
app.post("/api/screenings/rule",async c=>{try{const u=c.get("user") as AuthUser,b=await c.req.json<any>(),m=await appMeta(c.env.DB);if(!m.candidate)return c.json({error:"applications_missing_candidate_key"},500);const r=await c.env.DB.prepare(`SELECT a.id,j.title,j.description,cu.name,cp.skills,cp.experience_years,cp.summary FROM applications a JOIN jobs j ON j.id=a.job_id JOIN users cu ON cu.id=a.${m.candidate} LEFT JOIN candidate_profiles cp ON cp.user_id=cu.id WHERE a.id=? AND j.company_id=? LIMIT 1`).bind(b.application_id,u.company_id).first<any>();if(!r)return c.json({error:"application_not_found"},404);let skills:string[]=[];if(r.skills){try{skills=JSON.parse(r.skills)}catch{skills=String(r.skills).split(/[,|]/).map((x:string)=>x.trim()).filter(Boolean)}}const text=String(r.summary||"").toLowerCase(),hits=skills.filter(s=>text.includes(s.toLowerCase()));const score=skills.length?Math.round(hits.length/skills.length*100):(Number(r.experience_years||0)>0?70:50),status=score>=85?"Strong Match":score>=70?"Potential Match":"Low Match";if(m.cs.has("score"))await c.env.DB.prepare("UPDATE applications SET score=? WHERE id=?").bind(score,b.application_id).run();if(m.cs.has("status"))await c.env.DB.prepare("UPDATE applications SET status=? WHERE id=?").bind(status,b.application_id).run();await audit(c,u,"screening.rule",b.application_id);return c.json({overall_score:score,status,matched_skills:hits,missing_skills:skills.filter(s=>!hits.includes(s)),note:"Rule-based screening; recruiter makes the final decision."})}catch(e:any){return c.json({error:"rule_screen_failed",detail:String(e?.message||e)},500)}});
app.post("/api/ai/screen",async c=>{try{const u=c.get("user") as AuthUser;if(!c.env.OPENAI_API_KEY)return c.json({error:"ai_not_configured",message:"Set OPENAI_API_KEY as a Worker secret."},503);const b=await c.req.json<any>(),m=await appMeta(c.env.DB);if(!m.candidate)return c.json({error:"applications_missing_candidate_key"},500);const r=await c.env.DB.prepare(`SELECT a.id,j.title,j.description,cu.name,cp.summary,cp.skills,cp.experience_years FROM applications a JOIN jobs j ON j.id=a.job_id JOIN users cu ON cu.id=a.${m.candidate} LEFT JOIN candidate_profiles cp ON cp.user_id=cu.id WHERE a.id=? AND j.company_id=? LIMIT 1`).bind(b.application_id,u.company_id).first<any>();if(!r)return c.json({error:"application_not_found"},404);const schema={type:"object",additionalProperties:false,properties:{overall_score:{type:"integer",minimum:0,maximum:100},summary:{type:"string"},strengths:{type:"array",items:{type:"string"}},gaps:{type:"array",items:{type:"string"}},recommendation:{type:"string"},interview_questions:{type:"array",items:{type:"string"}}},required:["overall_score","summary","strengths","gaps","recommendation","interview_questions"]};const resp=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${c.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:c.env.OPENAI_MODEL||"gpt-5.6",store:false,instructions:"Assess job fit only from job-relevant evidence. Never infer protected traits. Return structured JSON only.",input:`JOB: ${r.title}\nDESCRIPTION: ${String(r.description).slice(0,14000)}\nCANDIDATE: ${r.name}\nPROFILE: SUMMARY=${r.summary||""}\nSKILLS=${r.skills||""}\nEXPERIENCE_YEARS=${r.experience_years||0}`,text:{format:{type:"json_schema",name:"candidate_screening",strict:true,schema}}})});if(!resp.ok)return c.json({error:"ai_request_failed",status:resp.status},502);const d=await resp.json() as any,content=d?.output?.flatMap((x:any)=>x?.content||[]).find((x:any)=>x?.type==="output_text")?.text;if(!content)return c.json({error:"empty_ai_response"},502);let result:any;try{result=JSON.parse(content)}catch{return c.json({error:"invalid_ai_json"},502)};result.status=result.overall_score>=85?"Strong Match":result.overall_score>=70?"Potential Match":"Low Match";if(m.cs.has("score"))await c.env.DB.prepare("UPDATE applications SET score=? WHERE id=?").bind(result.overall_score,b.application_id).run();if(m.cs.has("status"))await c.env.DB.prepare("UPDATE applications SET status=? WHERE id=?").bind(result.status,b.application_id).run();await audit(c,u,"screening.ai",b.application_id);return c.json(result)}catch(e:any){return c.json({error:"ai_screen_failed",detail:String(e?.message||e)},500)}});
app.get("/", (c) => c.html(`<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${c.env.APP_NAME}</title>
<style>
:root{font-family:Inter,system-ui,-apple-system,sans-serif;color:#10213b;background:#f6f8fb}body{margin:0}header{background:#fff;border-bottom:1px solid #e5eaf2;padding:18px 28px;display:flex;justify-content:space-between;align-items:center}main{max-width:1180px;margin:28px auto;padding:0 20px}.brand{display:flex;align-items:center;gap:12px;font-weight:800;font-size:22px}.brand img{width:42px;height:42px;object-fit:contain}.muted{color:#667085}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card{background:#fff;border:1px solid #e4e9f1;border-radius:16px;padding:20px;box-shadow:0 3px 14px #132b4a0a;margin-bottom:18px}.metric b{font-size:30px;display:block;margin-top:8px}.tabs{display:flex;gap:8px;margin:18px 0}.tabs button,.btn{border:0;border-radius:10px;padding:10px 14px;background:#0b66ff;color:white;cursor:pointer}.tabs button.secondary,.btn.secondary{background:#edf2f8;color:#20304a}.hidden{display:none}.auth{max-width:480px;margin:60px auto}.input{width:100%;box-sizing:border-box;padding:12px;border:1px solid #d7deea;border-radius:10px;margin:6px 0 12px}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:11px;border-bottom:1px solid #edf0f5}.pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#edf4ff}.danger{color:#b42318}.logo{max-width:58px;max-height:58px}@media(max-width:800px){.grid,.row{grid-template-columns:1fr}.grid{grid-template-columns:1fr 1fr}}
</style></head><body>
<div id="auth" class="auth card"><div class="brand"><img src="/logo.png" onerror="this.style.display='none'"><span>${c.env.APP_NAME}</span></div><h2 id="authTitle">Sign in</h2><p class="muted">Secure recruiter workspace with tenant isolation.</p><form id="authForm"><div id="orgField" class="hidden"><label>Organization</label><input class="input" id="org" autocomplete="organization"></div><label>Name</label><input class="input" id="name" autocomplete="name"><label>Email</label><input class="input" id="email" type="email" autocomplete="email" required><label>Password</label><input class="input" id="password" type="password" minlength="10" autocomplete="current-password" required><button class="btn" id="authBtn">Sign in</button></form><p><button class="btn secondary" id="toggleAuth">Create an organization</button></p><div id="authMsg" class="muted"></div></div>
<div id="app" class="hidden"><header><div class="brand"><img src="/logo.png" onerror="this.style.display='none'"><span>${c.env.APP_NAME}</span></div><div><span id="who" class="muted"></span> <button class="btn secondary" id="logout">Logout</button></div></header><main><div class="tabs"><button data-tab="overview">Overview</button><button class="secondary" data-tab="jobs">Jobs</button><button class="secondary" data-tab="candidates">Candidates</button><button class="secondary" data-tab="applications">Screening</button></div>
<section id="overview" class="tab"><div class="grid"><div class="card metric">Jobs<b id="mJobs">0</b></div><div class="card metric">Candidates<b id="mCandidates">0</b></div><div class="card metric">Applications<b id="mApplications">0</b></div><div class="card metric">Strong matches<b id="mStrong">0</b></div></div><div class="card"><h2>AI Screening</h2><p class="muted">Create jobs, upload CVs, attach candidates to jobs, then run rule-based or AI screening.</p></div></section>
<section id="jobs" class="tab hidden"><div class="card"><h2>Create job</h2><form id="jobForm"><div class="row"><input class="input" id="jobTitle" placeholder="Job title" required><input class="input" id="jobLocation" placeholder="Location"></div><textarea class="input" id="jobDescription" rows="6" placeholder="Job description" required></textarea><input class="input" id="jobSkills" placeholder="Skills, comma separated"><button class="btn">Create job</button></form></div><div class="card"><h2>Jobs</h2><table class="table"><thead><tr><th>Title</th><th>Location</th><th>Created</th></tr></thead><tbody id="jobsBody"></tbody></table></div></section>
<section id="candidates" class="tab hidden"><div class="card"><h2>Upload CV</h2><form id="candidateForm"><div class="row"><input class="input" id="candidateName" placeholder="Candidate name" required><input class="input" id="candidateEmail" placeholder="Email"></div><div class="row"><input class="input" id="candidatePhone" placeholder="Phone"><select class="input" id="candidateJob"><option value="">Attach to job (optional)</option></select></div><input class="input" id="candidateFile" type="file" accept=".pdf,.docx,.txt" required><button class="btn">Upload candidate</button><p id="candidateMsg" class="muted"></p></form></div><div class="card"><h2>Candidates</h2><table class="table"><thead><tr><th>Name</th><th>Email</th><th>CV</th></tr></thead><tbody id="candidatesBody"></tbody></table></div></section>
<section id="applications" class="tab hidden"><div class="card"><h2>Screening pipeline</h2><table class="table"><thead><tr><th>Candidate</th><th>Job</th><th>Score</th><th>Status</th><th>Actions</th></tr></thead><tbody id="appsBody"></tbody></table></div><div id="result" class="card hidden"><h2>Screening result</h2><pre id="resultText" style="white-space:pre-wrap"></pre></div></section>
</main></div>
<script>
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let registerMode=false;
async function api(path,opt={}){const r=await fetch(path,{credentials:'same-origin',...opt});const data=await r.json().catch(()=>({}));if(!r.ok){const base=data.error||'request_failed';const message=data.detail?base+': '+data.detail:base;throw new Error(message)}return data}
function setMode(){registerMode=!registerMode;$('#authTitle').textContent=registerMode?'Create organization':'Sign in';$('#authBtn').textContent=registerMode?'Create account':'Sign in';$('#orgField').classList.toggle('hidden',!registerMode);$('#name').required=registerMode;$('#toggleAuth').textContent=registerMode?'Back to sign in':'Create an organization'}
$('#toggleAuth').onclick=e=>{e.preventDefault();setMode()};
$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authMsg').textContent='Working...';try{const path=registerMode?'/api/auth/register':'/api/auth/login';const body=registerMode?{organization_name:$('#org').value,name:$('#name').value,email:$('#email').value,password:$('#password').value}:{email:$('#email').value,password:$('#password').value};await api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await boot()}catch(err){$('#authMsg').textContent=err.message}}
$('#logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()};
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.add('secondary'));b.classList.remove('secondary');$$('.tab').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.tab).classList.remove('hidden');if(b.dataset.tab==='jobs')loadJobs();if(b.dataset.tab==='candidates')loadCandidates();if(b.dataset.tab==='applications')loadApps()});
async function loadJobs(){const jobs=await api('/api/jobs');$('#jobsBody').innerHTML=jobs.map(j=>\`<tr><td>\${esc(j.title)}</td><td>\${esc(j.location||'-')}</td><td>\${new Date(j.created_at).toLocaleString()}</td></tr>\`).join('');$('#candidateJob').innerHTML='<option value="">Attach to job (optional)</option>'+jobs.map(j=>\`<option value="\${j.id}">\${esc(j.title)}</option>\`).join('')}
async function loadCandidates(){const rows=await api('/api/candidates');$('#candidatesBody').innerHTML=rows.map(x=>\`<tr><td>\${esc(x.name)}</td><td>\${esc(x.email||'-')}</td><td>\${esc(x.cv_filename||'-')}</td></tr>\`).join('')}
async function loadApps(){const rows=await api('/api/applications');$('#appsBody').innerHTML=rows.map(x=>\`<tr><td>\${esc(x.candidate_name)}</td><td>\${esc(x.job_title)}</td><td>\${x.score||0}</td><td><span class="pill">\${esc(x.status)}</span></td><td><button class="btn secondary" onclick="rule('\${x.id}')">Rule</button> <button class="btn" onclick="ai('\${x.id}')">AI</button></td></tr>\`).join('')}
async function refresh(){const d=await api('/api/dashboard');$('#mJobs').textContent=d.jobs;$('#mCandidates').textContent=d.candidates;$('#mApplications').textContent=d.applications;$('#mStrong').textContent=d.strong_matches;await loadJobs()}
$('#jobForm').onsubmit=async e=>{e.preventDefault();await api('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:$('#jobTitle').value,location:$('#jobLocation').value,description:$('#jobDescription').value,requirements:$('#jobSkills').value.split(',').map(x=>x.trim()).filter(Boolean)})});e.target.reset();await refresh();loadJobs()}
$('#candidateForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData();fd.append('name',$('#candidateName').value);fd.append('email',$('#candidateEmail').value);fd.append('phone',$('#candidatePhone').value);fd.append('job_id',$('#candidateJob').value);fd.append('file',$('#candidateFile').files[0]);$('#candidateMsg').textContent='Uploading...';try{const r=await api('/api/candidates/upload',{method:'POST',body:fd});$('#candidateMsg').textContent=r.extraction_status==='pending'?'Uploaded. PDF/DOCX text extraction is the next module.':'Uploaded and text indexed.';e.target.reset();await refresh();loadCandidates()}catch(err){$('#candidateMsg').textContent=err.message}}
window.rule=async id=>{try{const r=await api('/api/screenings/rule',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({application_id:id})});showResult(r);await refresh();loadApps()}catch(e){showResult({error:e.message})}}
window.ai=async id=>{try{const r=await api('/api/ai/screen',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({application_id:id})});showResult(r);await refresh();loadApps()}catch(e){showResult({error:e.message})}}
function showResult(x){$('#result').classList.remove('hidden');$('#resultText').textContent=JSON.stringify(x,null,2)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
async function boot(){try{const r=await api('/api/auth/me');$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');$('#who').textContent=r.user.name+' · '+r.user.company_name;await refresh()}catch{}}
boot();
</script></body></html>`));

app.notFound((c) => c.json({ error: "not_found" }, 404));

export default app;
